[wokwi]
version = 1
elf = 'test/blink/build/arduino.avr.uno/blink.ino.with_bootloader.bin'
firmware = 'test/blink/build/arduino.avr.uno/blink.ino.with_bootloader.hex'

[[chip]]
name = 'demultiplexer'
binary = 'dist/chip.wasm'